name: wallet
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons
    - assets/images

  fonts:
    - family: Monoska
      fonts:
        - asset: fonts/Monoska.ttf
    - family: Helios
      fonts:
        - asset: fonts/HeliosExtC-Bold.otf
          weight: 900
        - asset: fonts/HeliosExtC-Regular.otf
          weight: 400
    - family: SF-Pro
      fonts:
        - asset: fonts/SF-Pro-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Light.otf
          weight: 200
